// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DeathRaceGame$Type } from "./DeathRaceGame";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DeathRaceGame"]: DeathRaceGame$Type;
    ["contracts/DeathRaceGame.sol:DeathRaceGame"]: DeathRaceGame$Type;
  }

  interface ContractTypesMap {
    ["DeathRaceGame"]: GetContractReturnType<DeathRaceGame$Type["abi"]>;
    ["contracts/DeathRaceGame.sol:DeathRaceGame"]: GetContractReturnType<DeathRaceGame$Type["abi"]>;
  }
}
